/**
 * Loader for the golden values generated by `tests/app/parity_fixture.py`.
 *
 * Node-only — used by the parity tests, never bundled into the app.
 */

import { readFileSync } from "node:fs";
import type { Manifest } from "../operator";

export interface GammaCase {
  family: string;
  coupling: number;
  xi: number;
  sigma_sq: number;
  gamma: number;
  moment: number;
}

export interface CorrelatorCase {
  family: string;
  coupling: number;
  xi: number;
  gamma: number;
  log_r: number[];
  log_w: number[];
}

export interface BulkCase {
  r: number;
  eps: number;
  contact_integral: number;
  reduced: number;
  measured_log_coefficient: number;
}

export interface OperatorCase {
  index: number;
  log_m: number;
  v_phi: number[];
  log_r: number[];
  log_w: number[];
}

export interface Parity {
  background: {
    L: number;
    m_sq: number;
    delta: number;
    c_delta: number;
    log_coefficient: number;
    free_dimension: number;
    normalization_factor: number;
  };
  gamma_function: { x: number; value: number }[];
  gammas: GammaCase[];
  correlators: CorrelatorCase[];
  bulk: BulkCase[];
  phi_grid: number[];
  operator_cases: OperatorCase[];
}

function read(name: string): string {
  return readFileSync(new URL(name, import.meta.url), "utf8");
}

export function loadParity(): Parity {
  return JSON.parse(read("./parity.json")) as Parity;
}

export function loadManifest(): Manifest {
  return JSON.parse(read("./operator/manifest.json")) as Manifest;
}

export function loadWeights(): ArrayBuffer {
  const buffer = readFileSync(new URL("./operator/weights.bin", import.meta.url));
  return buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength) as ArrayBuffer;
}
