/**
 * Browser inference for the Fourier-DeepONet, reading the artifacts written by
 * `qft-operator-export`.
 *
 * This is a hand port of `qft_operator.models.deeponet.FourierDeepONet` rather than a
 * runtime like ONNX, because the spectral layers have no ONNX lowering (`aten::fft_rfft`
 * is unsupported at opset 17). Keeping the weights in Fourier space and doing the small
 * fixed-size transform here — see `fft.ts` — is both the compact and the fast option.
 *
 * Parity with PyTorch is pinned by `operator.test.ts` against golden values generated by
 * `tests/app/test_frontend_parity.py`, so a drift in either implementation fails a test
 * rather than silently changing what the page draws.
 */

import {
  conv1x1,
  gelu,
  groupNorm,
  interp1dUniform,
  layerNorm,
  linear,
  spectralConv,
} from "./nn";

export interface TensorEntry {
  name: string;
  shape: number[];
  offset: number;
  bytes: number;
}

export interface Architecture {
  n_phi: number;
  latent_dim: number;
  branch_spectral: boolean;
  branch_blocks: number;
  trunk_layers: number;
  spectral_mixing: boolean;
  context_grid: number;
  context_width: number;
  context_blocks: number;
  log_r_min: number;
  log_r_max: number;
  num_invariants: number;
  num_frequencies: number;
  radial_mode: "separation" | "rg_scale" | "geometric";
  translation_invariant: boolean;
  log_r_scale: number;
  head: "inner_product" | "attention";
  residual_mode: "none" | "free" | "exponent";
  free_dimension: number;
  L: number;
}

export interface Manifest {
  format: string;
  version: number;
  trained: boolean;
  spectral_form: "fourier" | "circular";
  dtype: "float32";
  /** Half-width of the physical field grid the branch input is sampled on. */
  phi_max: number;
  feature_scale: number;
  physics: Record<string, number>;
  architecture: Architecture;
  spectral_grid_sizes: Record<string, number>;
  tensors: TensorEntry[];
  total_bytes: number;
}

/** A loaded operator: weights indexed by name, plus the architecture that shaped them. */
export class Operator {
  private readonly weights = new Map<string, Float32Array>();
  private readonly shapes = new Map<string, number[]>();

  constructor(
    readonly manifest: Manifest,
    blob: ArrayBuffer,
  ) {
    if (manifest.format !== "qft-operator-weights") {
      throw new Error(`unexpected weight format ${manifest.format}`);
    }
    if (manifest.spectral_form !== "fourier") {
      throw new Error(
        `this runtime implements the "fourier" spectral form, got "${manifest.spectral_form}"`,
      );
    }
    if (manifest.architecture.head !== "inner_product") {
      throw new Error(`this runtime implements the inner-product head only`);
    }
    for (const entry of manifest.tensors) {
      // Offsets are multiples of 4 by construction, so a direct view is safe.
      this.weights.set(entry.name, new Float32Array(blob, entry.offset, entry.bytes / 4));
      this.shapes.set(entry.name, entry.shape);
    }
  }

  /** Fetch manifest and weights relative to a base URL. */
  static async load(baseUrl: string): Promise<Operator> {
    const manifest = (await (await fetch(`${baseUrl}/manifest.json`)).json()) as Manifest;
    const blob = await (await fetch(`${baseUrl}/weights.bin`)).arrayBuffer();
    return new Operator(manifest, blob);
  }

  private get(name: string): Float32Array {
    const tensor = this.weights.get(name);
    if (!tensor) throw new Error(`missing weight ${name}`);
    return tensor;
  }

  private shape(name: string): number[] {
    const shape = this.shapes.get(name);
    if (!shape) throw new Error(`missing weight ${name}`);
    return shape;
  }

  /** Number of retained Fourier modes of a spectral layer, from its weight shape. */
  private modes(path: string): number {
    return this.shape(`${path}.weight`)[2];
  }

  // ------------------------------------------------------------------ blocks --
  /** One FNO block: spectral + pointwise branch, normalized, gated, residual. */
  private fourierBlock(x: Float64Array, channels: number, length: number, path: string): Float64Array {
    const modes = this.modes(`${path}.spectral`);
    const spectral = spectralConv(
      x, channels, channels, length, this.get(`${path}.spectral.weight`), modes,
    );
    const pointwise = conv1x1(
      x, channels, length, this.get(`${path}.pointwise.weight`),
      this.get(`${path}.pointwise.bias`), channels,
    );
    const h = new Float64Array(spectral.length);
    for (let i = 0; i < h.length; i += 1) h[i] = spectral[i] + pointwise[i];

    const groups = Math.min(8, channels);
    groupNorm(h, channels, length, groups, this.get(`${path}.norm.weight`), this.get(`${path}.norm.bias`));
    gelu(h);
    const out = new Float64Array(h.length);
    for (let i = 0; i < out.length; i += 1) out[i] = x[i] + h[i];
    return out;
  }

  /** An MLP stack of `[Linear, LayerNorm, GELU] × k` followed by a final Linear. */
  private mlp(x: Float64Array, rows: number, inDim: number, path: string, depth: number): Float64Array {
    let current = x;
    let width = inDim;
    for (let i = 0; i < depth; i += 1) {
      const linearIndex = 3 * i;
      const normIndex = linearIndex + 1;
      const w = this.get(`${path}.net.${linearIndex}.weight`);
      const out = this.shape(`${path}.net.${linearIndex}.weight`)[0];
      current = linear(current, rows, width, w, this.get(`${path}.net.${linearIndex}.bias`), out);
      width = out;
      layerNorm(
        current, rows, width,
        this.get(`${path}.net.${normIndex}.weight`), this.get(`${path}.net.${normIndex}.bias`),
      );
      gelu(current);
    }
    const finalIndex = 3 * depth;
    const w = this.get(`${path}.net.${finalIndex}.weight`);
    const out = this.shape(`${path}.net.${finalIndex}.weight`)[0];
    return linear(current, rows, width, w, this.get(`${path}.net.${finalIndex}.bias`), out);
  }

  /** FiLM: features · (1 + scale(code)) + shift(code), broadcast over the row axis. */
  private film(
    features: Float64Array, rows: number, featureDim: number, code: Float64Array, path: string,
  ): Float64Array {
    const latent = code.length;
    const both = linear(
      code, 1, latent, this.get(`${path}.to_scale_shift.weight`),
      this.get(`${path}.to_scale_shift.bias`), 2 * featureDim,
    );
    const out = new Float64Array(features.length);
    for (let r = 0; r < rows; r += 1) {
      for (let f = 0; f < featureDim; f += 1) {
        out[r * featureDim + f] =
          features[r * featureDim + f] * (1 + both[f]) + both[featureDim + f];
      }
    }
    return out;
  }

  // ------------------------------------------------------------------ branch --
  /** Encode the potential samples into the latent operator code. */
  private branch(vPhi: Float64Array): Float64Array {
    const arch = this.manifest.architecture;
    const n = arch.n_phi;
    if (!arch.branch_spectral) {
      return this.mlp(vPhi, 1, n, "branch.head", 2);
    }

    const phiGrid = this.get("branch.phi_grid");
    const stacked = new Float64Array(2 * n);
    for (let i = 0; i < n; i += 1) {
      stacked[i] = vPhi[i];
      stacked[n + i] = phiGrid[i];
    }

    const width = this.shape("branch.lift.weight")[0];
    let h = conv1x1(stacked, 2, n, this.get("branch.lift.weight"), this.get("branch.lift.bias"), width);
    for (let b = 0; b < arch.branch_blocks; b += 1) {
      h = this.fourierBlock(h, width, n, `branch.blocks.${b}`);
    }

    // Mean and max pooling over the field grid, concatenated.
    const pooled = new Float64Array(2 * width);
    for (let c = 0; c < width; c += 1) {
      let mean = 0;
      let best = -Infinity;
      for (let i = 0; i < n; i += 1) {
        const value = h[c * n + i];
        mean += value;
        if (value > best) best = value;
      }
      pooled[c] = mean / n;
      pooled[width + c] = best;
    }
    return this.mlp(pooled, 1, 2 * width, "branch.head", 2);
  }

  // ------------------------------------------------------------------- trunk --
  /** Conformal invariants plus Fourier features: the metric-aware positional encoding. */
  private encoding(logR: Float64Array, logM: number): Float64Array {
    const arch = this.manifest.architecture;
    const points = logR.length;
    const invariants = arch.num_invariants;
    const scale = arch.log_r_scale;

    const raw = new Float64Array(points * invariants);
    for (let i = 0; i < points; i += 1) {
      let logZ: number;
      if (arch.radial_mode === "separation") logZ = logR[i] - Math.LN2;
      else if (arch.radial_mode === "rg_scale") logZ = -logM;
      else logZ = 0.5 * (logR[i] - Math.LN2 - logM);
      const logSqrtG = 2 * Math.log(arch.L) - 2 * logZ;
      raw[i * invariants] = logR[i] / scale;
      raw[i * invariants + 1] = logSqrtG / (2 * scale);
      raw[i * invariants + 2] = logM;
    }

    const projection = this.get("trunk.encoding.fourier.projection");
    const frequencies = arch.num_frequencies;
    const out = new Float64Array(points * (invariants + 2 * frequencies));
    const stride = invariants + 2 * frequencies;
    for (let i = 0; i < points; i += 1) {
      for (let k = 0; k < invariants; k += 1) out[i * stride + k] = raw[i * invariants + k];
      for (let f = 0; f < frequencies; f += 1) {
        let projected = 0;
        for (let k = 0; k < invariants; k += 1) {
          projected += raw[i * invariants + k] * projection[k * frequencies + f];
        }
        projected *= 2 * Math.PI;
        out[i * stride + invariants + f] = Math.sin(projected);
        out[i * stride + invariants + frequencies + f] = Math.cos(projected);
      }
    }
    return out;
  }

  /** Non-local boundary features, built on the internal reference grid and interpolated. */
  private context(logR: Float64Array, code: Float64Array, logM: number): Float64Array {
    const arch = this.manifest.architecture;
    const grid = this.get("trunk.context.grid");
    const size = arch.context_grid;
    const width = arch.context_width;
    const scale = 0.5 * (arch.log_r_max - arch.log_r_min);

    const channels = new Float64Array(2 * size);
    for (let i = 0; i < size; i += 1) {
      channels[i] = grid[i] / scale;
      channels[size + i] = logM;
    }

    let field = conv1x1(
      channels, 2, size, this.get("trunk.context.seed.weight"),
      this.get("trunk.context.seed.bias"), width,
    );
    // FiLM acts on (grid, width), so transpose in and back out.
    const transposed = new Float64Array(size * width);
    for (let c = 0; c < width; c += 1) {
      for (let g = 0; g < size; g += 1) transposed[g * width + c] = field[c * size + g];
    }
    const modulated = this.film(transposed, size, width, code, "trunk.context.film");
    field = new Float64Array(width * size);
    for (let c = 0; c < width; c += 1) {
      for (let g = 0; g < size; g += 1) field[c * size + g] = modulated[g * width + c];
    }

    for (let b = 0; b < arch.context_blocks; b += 1) {
      field = this.fourierBlock(field, width, size, `trunk.context.blocks.${b}`);
    }
    return interp1dUniform(field, width, size, arch.log_r_min, arch.log_r_max, logR);
  }

  /** Evaluate the conditioned latent basis at the query separations. */
  private trunk(logR: Float64Array, code: Float64Array, logM: number): Float64Array {
    const arch = this.manifest.architecture;
    const points = logR.length;
    const encoded = this.encoding(logR, logM);
    const encodedDim = arch.num_invariants + 2 * arch.num_frequencies;

    let features = encoded;
    let featureDim = encodedDim;
    if (arch.spectral_mixing) {
      const ctx = this.context(logR, code, logM);
      featureDim = encodedDim + arch.context_width;
      features = new Float64Array(points * featureDim);
      for (let i = 0; i < points; i += 1) {
        for (let k = 0; k < encodedDim; k += 1) {
          features[i * featureDim + k] = encoded[i * encodedDim + k];
        }
        for (let k = 0; k < arch.context_width; k += 1) {
          features[i * featureDim + encodedDim + k] = ctx[i * arch.context_width + k];
        }
      }
    }

    const width = this.shape("trunk.lift.weight")[0];
    const h = linear(
      features, points, featureDim, this.get("trunk.lift.weight"),
      this.get("trunk.lift.bias"), width,
    );

    for (let l = 0; l < arch.trunk_layers; l += 1) {
      const modulated = this.film(h, points, width, code, `trunk.films.${l}`);
      layerNorm(
        modulated, points, width,
        this.get(`trunk.layers.${l}.0.weight`), this.get(`trunk.layers.${l}.0.bias`),
      );
      let inner = linear(
        modulated, points, width, this.get(`trunk.layers.${l}.1.weight`),
        this.get(`trunk.layers.${l}.1.bias`), width,
      );
      gelu(inner);
      inner = linear(
        inner, points, width, this.get(`trunk.layers.${l}.4.weight`),
        this.get(`trunk.layers.${l}.4.bias`), width,
      );
      for (let i = 0; i < h.length; i += 1) h[i] += inner[i];
    }

    return linear(
      h, points, width, this.get("trunk.project.weight"), this.get("trunk.project.bias"),
      arch.latent_dim,
    );
  }

  /** Network output before the residual reparametrization. */
  private rawOutput(vPhi: Float64Array, logR: Float64Array, logM: number): Float64Array {
    const arch = this.manifest.architecture;
    const code = this.branch(vPhi);
    const basis = this.trunk(logR, code, logM);
    const points = logR.length;

    const product = new Float64Array(points * arch.latent_dim);
    for (let i = 0; i < points; i += 1) {
      for (let k = 0; k < arch.latent_dim; k += 1) {
        product[i * arch.latent_dim + k] = code[k] * basis[i * arch.latent_dim + k];
      }
    }
    return linear(
      product, points, arch.latent_dim, this.get("readout.weight"), this.get("readout.bias"), 1,
    );
  }

  /**
   * Predict log W at the given separations.
   *
   * @param vPhi Potential samples on the field grid, already divided by the manifest's
   *   `feature_scale` — see {@link scaleFeatures}.
   * @param logR Query separations in log space.
   * @param logM The renormalization scale.
   */
  predictLogW(vPhi: Float64Array, logR: Float64Array, logM: number): Float64Array {
    const arch = this.manifest.architecture;
    if (vPhi.length !== arch.n_phi) {
      throw new Error(`expected ${arch.n_phi} field samples, got ${vPhi.length}`);
    }

    if (arch.residual_mode === "exponent") {
      // The head is evaluated once at r = 1, so the exponent carries no residual
      // r-dependence and the output is an exact power law.
      const gamma = this.rawOutput(vPhi, new Float64Array([0]), logM)[0];
      const out = new Float64Array(logR.length);
      for (let i = 0; i < logR.length; i += 1) {
        out[i] = -2 * (arch.free_dimension - gamma) * logR[i];
      }
      return out;
    }

    const raw = this.rawOutput(vPhi, logR, logM);
    const out = new Float64Array(logR.length);
    for (let i = 0; i < logR.length; i += 1) {
      out[i] = arch.residual_mode === "none" ? raw[i] : -2 * arch.free_dimension * logR[i] + raw[i];
    }
    return out;
  }

  /** Divide a potential by the training-time normalization, as the dataset did. */
  scaleFeatures(vPhi: Float64Array): Float64Array {
    const scale = this.manifest.feature_scale || 1;
    const out = new Float64Array(vPhi.length);
    for (let i = 0; i < vPhi.length; i += 1) out[i] = vPhi[i] / scale;
    return out;
  }

  /**
   * The branch's normalized coordinate channel, spanning [−1, 1].
   *
   * Not the physical field grid: the branch is fed the potential *and* a coordinate
   * channel so it knows where on the φ axis each sample sits, and that channel is
   * normalized. The physical grid the samples must be taken on is
   * [−{@link phiMax}, {@link phiMax}].
   */
  get coordinateChannel(): Float32Array {
    return this.get("branch.phi_grid");
  }

  /** Half-width of the physical field grid the branch input must be sampled on. */
  get phiMax(): number {
    return this.manifest.phi_max;
  }

  /** The physical field grid, matching what the training data used. */
  get phiGrid(): Float64Array {
    const n = this.manifest.architecture.n_phi;
    const max = this.phiMax;
    const grid = new Float64Array(n);
    for (let i = 0; i < n; i += 1) grid[i] = -max + (2 * max * i) / (n - 1);
    return grid;
  }
}
